### ISSUE TITLE
reason of thresholding images between -100 and 240 HU

### ISSUE THREAD

**Issue by snapfinger** [198808xc/OrganSegC2F#1]
Hi Lingxi, thanks for your code. I have a question regarding the thresholding operation you do in [init.py](https://github.com/198808xc/OrganSegC2F/blob/34b304250bf2e75e2b9fd560ce0bd95c0de89495/OrganSegC2F/init.py#L81), where you threshold the image to the range between -100 and 240, I wonder what is the scientific evidence to use these two values? 

Thanks!

**Comment by 198808xc** [comment]
Hi,

Thanks for your interest.

Actually this window (a.k.a, the soft tissue window) was borrowed from some previous work, such as one of our baselines [A]. They used [-160, 240] and we used [-100, 240]. According to our experiments, the segmentation accuracy is not sensitive to these numbers.

We also tried to perform statistics on all pancreas pixels (using the ground-truth). You may try yourself. It would lead to the same conclusion.

[A] Roth et.al, Spatial Aggregation of Holistically-Nested Networks for Automated Pancreas Segmentation, MICCAI 2016.
