### ISSUE TITLE
run out of memory in coarse2fine_testing Z axis

### ISSUE THREAD

**Issue by iverson333** [198808xc/OrganSegC2F#4]
Hi Lingxi, I tried running your script, and there's no problem until the coarse2fine_testing, where I faced the following issue. Would you give any suggestions on it?

F1221 10:07:08.287941 43706 syncedmem.cpp:71] Check failed: error == cudaSuccess (2 vs. 0)  out of memory

*** Check failure stack trace: ***
Coarse-scaled result directory for plane X: /data/mstr/alex/model1/data/results/coarse:1e-5/FD0:XC3_1_20170924_115008/volumes .
Coarse-scaled result directory for plane Y: /data/mstr/alex/model1/data/results/coarse:1e-5/FD0:YC3_1_20170925_085844/volumes .
Coarse-scaled result directory for plane Z: /data/mstr/alex/model1/data/results/coarse:1e-5/FD0:ZC3_1_20170926_090834/volumes .
Snapshot directory: /data/mstr/alex/model1/data/models/snapshots/fine:1e-4,20/FD0:XF3_1_20171219_121949 .
1 snapshots are to be evaluated.
  Snapshot #1: /data/mstr/alex/model1/data/models/snapshots/fine:1e-4,20/FD0:XF3_1_20171219_121949/train_iter_60000.caffemodel .
Snapshot directory: /data/mstr/alex/model1/data/models/snapshots/fine:1e-4,20/FD0:YF3_1_20171219_121949 .
1 snapshots are to be evaluated.
  Snapshot #1: /data/mstr/alex/model1/data/models/snapshots/fine:1e-4,20/FD0:YF3_1_20171219_121949/train_iter_60000.caffemodel .
Snapshot directory: /data/mstr/alex/model1/data/models/snapshots/fine:1e-4,20/FD0:ZF3_1_20171219_121949 .
1 snapshots are to be evaluated.
  Snapshot #1: /data/mstr/alex/model1/data/models/snapshots/fine:1e-4,20/FD0:ZF3_1_20171219_121949/train_iter_60000.caffemodel .
Testing 1 out of 20 testcases.
  Data loading is finished: 0.315879106522 second(s) elapsed.
  Iteration round 0:
    Testing result is loaded: 0.512225151062 second(s) elapsed.
      DSC = 2 * 49466 / (54997 + 78329) = 0.742030811695 .
  Iteration round 1:
    Testing on plane X and snapshot 1 is finished: 5.94387221336 second(s) elapsed.
    Testing on plane Y and snapshot 1 is finished: 14.5347812176 second(s) elapsed.

./run.sh: line 392: 43706 Aborted                 (core dumped) python coarse2fine_testing.py $DATA_PATH $CURRENT_FOLD $ORGAN_NUMBER $LOW_RANGE $HIGH_RANGE $COARSE2FINE_TESTING_ORGAN_ID $COARSE2FINE_TESTING_GPU $COARSE_SLICE_THICKNESS $COARSE_LEARNING_RATE $COARSE_GAMMA $COARSE_TESTING_STARTING_ITERATIONS $COARSE_TESTING_STEP $COARSE_TESTING_MAX_ITERATIONS $COARSE_THRESHOLD $COARSE_TIMESTAMP_X $COARSE_TIMESTAMP_Y $COARSE_TIMESTAMP_Z $COARSE_FUSION_CODE $FINE_SLICE_THICKNESS $FINE_TRAINING_MARGIN $FINE_LEARNING_RATE $FINE_GAMMA $FINE_TESTING_STARTING_ITERATIONS $FINE_TESTING_STEP $FINE_TESTING_MAX_ITERATIONS $FINE_THRESHOLD $FINE_TIMESTAMP_X $FINE_TIMESTAMP_Y $FINE_TIMESTAMP_Z $COARSE2FINE_TESTING_MARGIN $MAX_ROUNDS`

It seemed to be the problem in the forward pass in Z axis (it corresponds to axial view right?) in code below. 
I used the same machine for training and testing. It's so wired to me that it can take training but fails testing!

    net.blobs['data'].reshape(*image_.shape)
                            net.blobs['data'].data[...] = image_
                            net.forward()
                            out = net.blobs['prob'].data[0, :, :, :]

**Comment by 198808xc** [comment]
Hello,

Thanks for your interest to our project.

One of my students once encountered the same problem as you did, and the problem seems to come from CUDNN. I guess you did not compile CUDNN in CAFFE, and, strangely, this increased the memory usage and caused the above problem.

As a reminder, after our people tried to recompile CAFFE with CUDNN, the memory issue is no longer existing, but the problem went into another problem, that the testing results are 0 for all iterations. I don't know if this weird issue will happen again, but if you did, maybe you can try to retrain these models using CAFFE with CUDNN.

Anyway, if the second issue happens, please kindly let us know, and we will try our best to help.

Best,
Lingxi

**Comment by iverson333** [comment]
Hey Lingxi, thank you for your prompt response! It's true that I didn't compile Cudnn in Caffe. I'll try that and see.
