### ISSUE TITLE
I have a problem: how to reconstruct the cropped images to original images? It seems that the location of rois changes after cropping the images.

### ISSUE THREAD

**Issue by Kristin-ZLCHEN** [198808xc/OrganSegC2F#6]

**Comment by 198808xc** [comment]
Sorry, but I am not sure what you meant by "reconstruct the cropped images to original images". When we crop the ROI from the original image, we record the coordinates, by which we can place the segmentation results on the cropped image onto the corresponding position of the original image.

Let me know if you have further questions. Good luck!

**Comment by Kristin-ZLCHEN** [comment]
Thanks for you repy. Whether rhe recorded coordinates are the values of  (minx:maxx, miny:maxy, minz:maxz)?

**Comment by 198808xc** [comment]
Yes. You may read the code through and it should be easy to understand the design logic.

**Comment by Kristin-ZLCHEN** [comment]
Thanks for your reply.
